steps:
  - label: ":books: Build spec"
    command:
      # Install the python dependencies necessary to build the spec
      - python3 -m venv env && . env/bin/activate
      - pip install -r scripts/requirements.txt
      # Build the spec
      - scripts/generate-matrix-org-assets
    artifact_paths:
      - assets.tar.gz
    plugins:
      - docker#v3.7.0:
          image: python:3.9

  - label: "rebuild matrix.org"
    trigger: "matrix-dot-org"
    async: true
    branches: "master"
