# Copyright 2016 OpenMarket Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

swagger: '2.0'
info:
  title: "Matrix Client-Server Notifications API"
  version: "1.0.0"
host: localhost:8008
schemes:
  - https
  - http
basePath: /_matrix/client/%CLIENT_MAJOR_VERSION%
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  $ref: definitions/security.yaml
paths:
  "/notifications":
    get:
      summary: Gets a list of events that the user has been notified about
      description: |-
        This API is used to paginate through the list of events that the
        user has been, or would have been notified about.
      operationId: getNotifications
      security:
        - accessToken: []
      parameters:
        - in: query
          type: string
          name: from
          description: Pagination token given to retrieve the next set of events.
          required: false
          x-example: "xxxxx"
        - in: query
          type: integer
          name: limit
          description: Limit on the number of events to return in this request.
          required: false
          x-example: 20
        - in: query
          name: only
          type: string
          description: |-
            Allows basic filtering of events returned. Supply ``highlight``
            to return only events where the notification had the highlight
            tweak set.
          required: false
          x-example: "highlight"
      responses:
        200:
          description: A batch of events is being returned
          examples:
            application/json: {
                "next_token": "abcdef",
                "notifications": [
                  {
                    "actions": [
                      "notify"
                    ],
                    "profile_tag": "hcbvkzxhcvb",
                    "read": true,
                    "room_id": "!abcdefg:example.com",
                    "ts": 1475508881945,
                    "event": {
                      "sender": "@alice:example.com",
                      "type": "m.room.message",
                      "age": 124524,
                      "txn_id": "1234",
                      "content": {
                        "body": "I am a fish",
                        "msgtype": "m.text"
                      },
                      "origin_server_ts": 1417731086797,
                      "event_id": "$74686972643033:example.com"
                    }
                  }
                ]
              }
          schema:
            type: object
            required: ["notifications"]
            properties:
              next_token:
                type: string
                description: |-
                  The token to supply in the ``from`` param of the next
                  ``/notifications`` request in order to request more
                  events. If this is absent, there are no more results.
              notifications:
                type: array
                items:
                  type: object
                  required: ["actions", "event", "read", "room_id", "ts"]
                  title: Notification
                  properties:
                    actions:
                      type: array
                      description: |-
                        The action(s) to perform when the conditions for this rule are met.
                        See `Push Rules: API`_.
                      items:
                        type:
                        - object
                        - string
                    event:
                      type: object
                      title: Event
                      description: The Event object for the event that triggered the notification.
                      properties:
                        event_id:
                          description: The ID of this event, if applicable.
                          type: string
                        content:
                          description: The content of this event. The fields in this object will vary depending
                            on the type of event.
                          title: EventContent
                          type: object
                        origin_server_ts:
                          description: Timestamp in milliseconds on originating homeserver when this event
                            was sent.
                          format: int64
                          type: integer
                        sender:
                          description: The MXID of the user who sent this event.
                          type: string
                        state_key:
                          description: Optional. This key will only be present for state events. A unique
                            key which defines the overwriting semantics for this piece of room state.
                          type: string
                        type:
                          description: The type of event.
                          type: string
                        unsigned:
                          description: Information about this event which was not sent by the originating
                            homeserver
                          properties:
                            age:
                              description: Time in milliseconds since the event was sent.
                              format: int64
                              type: integer
                            prev_content:
                              description: Optional. The previous ``content`` for this state. This will
                                be present only for state events appearing in the ``timeline``. If this
                                is not a state event, or there is no previous content, this key will be
                                missing.
                              title: EventContent
                              type: object
                            transaction_id:
                              description: Optional. The transaction ID set when this message was sent.
                                This key will only be present for message events sent by the device calling
                                this API.
                              type: string
                            redacted_because:
                              description: Optional. The event that redacted this event, if any.
                              title: Event
                              type: object
                          title: Unsigned
                          type: object
                    profile_tag:
                      type: string
                      description: The profile tag of the rule that matched this event.
                    read:
                      type: boolean
                      description: |-
                        Indicates whether the user has sent a read receipt indicating
                        that they have read this message.
                    room_id:
                      type: string
                      description: The ID of the room in which the event was posted.
                    ts:
                      format: int64
                      type: integer
                      description: |-
                        The unix timestamp at which the event notification was sent,
                        in milliseconds.
                description: The list of events that triggered notifications.
      tags:
        - Push notifications
