swagger: '2.0'
info:
  title: "Matrix Client-Server v1 message event send API"
  version: "1.0.0"
host: localhost:8008
schemes:
  - https
  - http
basePath: /_matrix/client/api/v1
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  accessToken:
    type: apiKey
    description: The user_id or application service access_token
    name: access_token
    in: query
paths:
  "/rooms/{roomId}/send/{eventType}/{txnId}":
    put:
      summary: Send a message event to the given room.
      description: |-
        This endpoint is used to send a message event to a room. Message events
        allow access to historical events and pagination, making them suited
        for "once-off" activity in a room.

        The body of the request should be the content object of the event; the
        fields in this object will vary depending on the type of event. See
        `Room Events`_ for the m. event specification.
      security:
        - accessToken: []
      parameters:
        - in: path
          type: string
          name: roomId
          description: The room to send the event to.
          required: true
          x-example: "!636q39766251:example.com"
        - in: path
          type: string
          name: eventType
          description: The type of event to send.
          required: true
          x-example: "m.room.message"
        - in: path
          name: txnId
          type: string
          description: |-
            The transaction ID for this event. Clients should generate a
            unique ID; it will be used by the server to ensure idempotency of requests.
          required: true
          x-example: "35"
        - in: body
          name: body
          schema:
            type: object
            example: |-
              {
                "msgtype": "m.text",
                "body": "hello"
              }
      responses:
        200:
          description: "An ID for the sent event."
          examples:
            application/json: |-
              {
                  "event_id": "YUwRidLecu"
              }
          schema:
            type: object
            properties:
              event_id:
                type: string
                description: |-
                  A unique identifier for the event.
