swagger: '2.0'
info:
  title: "Matrix Client-Server Voice over IP API"
  version: "1.0.0"
host: localhost:8008
schemes:
  - https
  - http
basePath: /_matrix/client/%CLIENT_MAJOR_VERSION%
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  accessToken:
    type: apiKey
    description: The user_id or application service access_token
    name: access_token
    in: query
paths:
  "/voip/turnServer":
    get:
      summary: Obtain TURN server credentials.
      description: |-
        This API provides credentials for the client to use when initiating
        calls.
      security:
        - accessToken: []
      responses:
        200:
          description: The TURN server credentials.
          examples:
            application/json: |-
              {
                "username":"1443779631:@user:example.com",
                "password":"JlKfBy1QwLrO20385QyAtEyIv0=",
                "uris":[
                  "turn:turn.example.com:3478?transport=udp",
                  "turn:10.20.30.40:3478?transport=tcp",
                  "turns:10.20.30.40:443?transport=tcp"
                ],
                "ttl":86400
              }
          schema:
            type: object
            properties:
              username:
                type: string
                description: |-
                  The username to use.
              password:
                type: string
                description: |-
                  The password to use.
              uris:
                type: array
                items:
                  type: string
                description: A list of TURN URIs
              ttl:
                type: integer
                description: The time-to-live in seconds
            required: ["username", "password", "uris", "ttl"]
        429:
          description: This request was rate-limited.
          schema:
            "$ref": "definitions/error.json"

